In [3]:
import numpy as np

In [4]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [5]:
x.mean()

2.0

In [6]:
(x-x.mean())/x.std()

array([-1.22474487,  0.        ,  1.22474487])

In [8]:
np.arange(1000)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
import sys 
import numpy as np  

py_list = list(range(1000)) #more: has overhead info each element is an object.. 
np_array = np.arange(1000)  #contigious memory block
print("Size of Python list: ", sys.getsizeof(py_list)) # sizeof only shows sizeof the list container.  if we had nested lists, we wouldnt be seeing it's memory. i.e memory of elementsnot shown
print("Size of Numpy array: ", sys.getsizeof(np_array)) 

Size of Python list:  8056
Size of Numpy array:  4112


In [12]:
import time  

# Define two Python lists 
py_list1 = list(range(1000000)) 
py_list2 = list(range(1000000, 2000000))  

# Define two Numpy arrays 
np_array1 = np.arange(1000000) 
np_array2 = np.arange(1000000, 2000000)  

# Adding Python lists 
start_time = time.time() 
result_list = [a + b for a, b in zip(py_list1, py_list2)] 
print("Time taken to add Python lists: ", time.time() - start_time)  

# Adding Numpy arrays 
start_time = time.time() 
result_array = np_array1 + np_array2 
print("Time taken to add Numpy arrays: ", time.time() - start_time)

Time taken to add Python lists:  0.0856635570526123
Time taken to add Numpy arrays:  0.0


In [18]:
np_array1 = np.array(["anusha","parashar"]) 
np_array2 = np.array(["Anusha","Aarashar"]) 
result_array = np.char.add(np_array1, np_array2)
result_array

array(['anushaAnusha', 'parasharAarashar'], dtype='<U16')

## sizes, shapes, memory
- shape 
- ndim
- size 
- np.nbytes

In [19]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.ndim #num of dimensions

2

In [ ]:
a.shape #shape of each dimension 3 rows, 4 columns 

(3, 4)

In [ ]:
a.size #num of elements 

12

In [32]:
arr3d = np.array([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                  [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]],
                  [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                  [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]]])
arr3d

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]],


       [[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]]]])

In [ ]:
print(arr3d.ndim) #3
print(arr3d.shape)# 3,4,2(wrong) --->correct is: dim...,row,column
print(arr3d.size) #24

4
(2, 2, 3, 4)
48


## Create Array
- np.zeros
- np.ones
- np.empty ---> random init, speed good

*creating spaced arrays/sequenced stuff*

- np.arrange(till where i want(not included))
- np.arrange(start, stop(not inc), skip)
- np.linspace(start, stop(INC), num= how many i want in betw start and stop)

In [37]:
np.empty(3) 

array([-1.22474487,  0.        ,  1.22474487])

In [ ]:
# np.ones(2,2,1,4)
# wrong, because only 1D array ** correction, you can just do, np.ones((2,1,4))
'''
[[[[- - - -]],
[[- - - -]]],

[[[- - - -]],
[[- - - -]]]]
'''
np.ones(2)

array([1., 1.])

In [64]:
np.ones((2,2,1,4))

array([[[[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]]]])

In [48]:
np.zeros(5)
np.zeros(5, dtype=int)


array([0, 0, 0, 0, 0])

In [45]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [47]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

## matrix

- np.eye(4) prints identity matrix
- np.ones((2,2,2))

In [50]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
np.ones((3,2,3,4))

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

### random matx

In [72]:
rng = np.random.default_rng().random(3)
rng

array([0.04287362, 0.23963091, 0.10202604])

In [75]:
rng = np.random.random((3,2))
rng

array([[0.30316223, 0.67273114],
       [0.15507665, 0.54690963],
       [0.00309282, 0.48245144]])

In [81]:
random_uniform = np.random.rand(3)
random_normal = np.random.randn(3)
print(random_uniform.shape)
print(random_normal)

(3,)
[1.49769234 0.56731377 1.147889  ]
